// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_xhWksP6FX65nDhX2M8XyCj1HFrzmvK4',
    appId: '1:794233388657:web:34d511eb790562a3f425d0',
    messagingSenderId: '794233388657',
    projectId: 'flutterassignment3',
    authDomain: 'flutterassignment3.firebaseapp.com',
    storageBucket: 'flutterassignment3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClBXOFDq7K2Av4V3cF3ZZ78GmE9KzkbW4',
    appId: '1:794233388657:android:be35a6d0c6abbc6bf425d0',
    messagingSenderId: '794233388657',
    projectId: 'flutterassignment3',
    storageBucket: 'flutterassignment3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsAU4yxo_qKoCB6AwRBJ4m0ZCtodj6XZQ',
    appId: '1:794233388657:ios:d286ef1b07fe1a69f425d0',
    messagingSenderId: '794233388657',
    projectId: 'flutterassignment3',
    storageBucket: 'flutterassignment3.appspot.com',
    iosBundleId: 'com.example.mdev1005Assignment3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsAU4yxo_qKoCB6AwRBJ4m0ZCtodj6XZQ',
    appId: '1:794233388657:ios:d286ef1b07fe1a69f425d0',
    messagingSenderId: '794233388657',
    projectId: 'flutterassignment3',
    storageBucket: 'flutterassignment3.appspot.com',
    iosBundleId: 'com.example.mdev1005Assignment3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_xhWksP6FX65nDhX2M8XyCj1HFrzmvK4',
    appId: '1:794233388657:web:cc070d2cdaf36f1ff425d0',
    messagingSenderId: '794233388657',
    projectId: 'flutterassignment3',
    authDomain: 'flutterassignment3.firebaseapp.com',
    storageBucket: 'flutterassignment3.appspot.com',
  );

}